// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Announcement is the predicate function for announcement builders.
type Announcement func(*sql.Selector)

// Ban is the predicate function for ban builders.
type Ban func(*sql.Selector)

// Maps is the predicate function for maps builders.
type Maps func(*sql.Selector)

// Report is the predicate function for report builders.
type Report func(*sql.Selector)

// Textures is the predicate function for textures builders.
type Textures func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
